### ISSUE TITLE
Reiter kann in einer Veranstaltung von Studierenden nicht aufgerufen werden

### ISSUE THREAD

**Issue by tleilax** [elan-ev/studip-opencast-plugin#156]
Seit kurzem haben wir das Problem, dass Studierende in manchen Veranstaltungen den OpenCast-Reiter nicht aufrufen können. Als Root oder Dozent geht alles wie erwartet. Bei Studierenden mit Status "autor" in der Veranstaltung und globalem Status "tutor" erscheint beim Aufruf des Reiters folgende Fehlermeldung im Log:

```
2019/05/06 11:29:46 [error] 19824#19824: *36560980 FastCGI sent in stderr: "PHP message: InvalidArgumentException: navigation item 'course/opencast/overview' not found in /var/www/studip-4.0/lib/navigation/Navigation.php:126
Stack trace:
#0 /var/www/studip-4.0/lib/navigation/Navigation.php(61): Navigation::getItem('course/opencast...')
#1 /var/www/studip-4.0/public/plugins_packages/elan-ev/OpenCast/controllers/course.php(168): Navigation::activateItem('course/opencast...')
#2 /var/www/studip-4.0/vendor/trails/trails.php(557): CourseController->index_action('1d9daaab-5200-4...')
#3 /var/www/studip-4.0/app/controllers/studip_controller.php(127): Trails_Controller->perform('index/1d9daaab-...')
#4 /var/www/studip-4.0/vendor/trails/trails.php(154): StudipController->perform('index/1d9daaab-...')
#5 /var/www/studip-4.0/vendor/trails/trails.php(121): Trails_Dispatcher->map_uri_to_response('course/index/1d...')
#6 /var/www/studip-4.0/lib/plugins/core/StudIPPlugin.class.php(131): Trails_Dispatcher->dispatch('course/index/1d...')
#7 /var/www/studip-4.0/public/plugins.php(54): StudIPPlugin" while reading response header from upstream, client: 134.106.48.220, server: elearning.uni-oldenburg.de, request: "GET /plugins.php/opencast/course/index/1d9daaab-5200-48af-8280-aa4d82e6c437?cid=4eeea806d00f7232de3857db33a9b828 HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "elearning.uni-oldenburg.de"
```

**Comment by nimuelle** [comment]
Das Plugin ist aktiv,  aber der Reiter ist auf "unsichtbar". D.h. die Dozentin hat wahrscheinlich einen Direktlink verschickt und nicht darauf geachtet, dass der Reiter gar nicht sichtbar ist. 

2 Ideen:
1. Wenn Reiter nicht sichtbar ist und man kommt mit einen Link, sollte man ggf. drauf hinweisen, dass zur Zeit keine Inhalte verfügbar sind.
2. Wenn man auf Unsichtbar als Dozent gestellt hat, sollte man vielleicht oben den Hinweis(Infobox) anzeigen, dass die Studis die Videos auch nicht sehen können.
