### ISSUE TITLE
LTI Upload Fehler , Konfiguration auf Opencast Seite notwendig?

### ISSUE THREAD

**Issue by olio2** [elan-ev/studip-opencast-plugin#274]
Beim Upload wird bei Opencast createMediaPackage, addDCCatlog und addTrack erfolgreich aufgerufen. Der Folgende POST zu ingest schläft aber immer mit "500 Internal Server Error" fehlt.

Im OC Log dazu:
2020-04-24T11:21:54,267 | WARN  | (IngestRestService:1152) - Unable to ingest mediapackage
java.lang.IllegalStateException: org.opencastproject.security.api.UnauthorizedException: Not allowed to set property on episode 9d630e1c-5a49-436f-a0bd-659903e9f7e3
	at org.opencastproject.ingest.impl.IngestServiceImpl.ingest(IngestServiceImpl.java:1123) ~[?:?]
	at org.opencastproject.ingest.endpoint.IngestRestService$1.xapply(IngestRestService.java:1142) ~[?:?]
	at org.opencastproject.ingest.endpoint.IngestRestService$1.xapply(IngestRestService.java:1125) ~[?:?]
	at org.opencastproject.util.data.Function0$X.apply(Function0.java:58) ~[57:opencast-common:8.3.0]
	at org.opencastproject.ingest.endpoint.IngestRestService.ingest(IngestRestService.java:1148) [92:opencast-ingest-service-impl:8.3.0]

**Comment by luniki** [comment]
@CGreweling Das scheint mir eine Hosting-Frage zu sein, die du besser beantworten kannst.
