### ISSUE TITLE
Verknüpfen bestehender Serien wird Dozenten nicht mehr angezeigt.

### ISSUE THREAD

**Issue by JFD23** [elan-ev/studip-opencast-plugin#326]
Bug oder Feature oder falsche Einstellung meinerseits?

Als Root wird es mir angezeigt. Endet aber oft in SQL Errors. 

`Typ: PDOException
Nachricht: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''f7a00285-30f3-4e50-a7a5-e290b2ef654f' ,`dbg_info` = NULL ,`mkdate` = 1596713181' at line 1
Code: 42000
Stack trace:
#$ lib/classes/StudipPDO.class.php(148)
#0 lib/classes/StudipPDO.class.php(148): PDO->exec('INSERT INTO `lo...')
#1 lib/models/SimpleORMap.class.php(1770): StudipPDO->exec('INSERT INTO `lo...')
#2 lib/classes/StudipLog.class.php(79): SimpleORMap->store()
#3 public/plugins_packages/elan-ev/OpenCast/controllers/course.php(312): StudipLog::log('OC_CONNECT_SERI...', NULL, '2a4373718e38db0...', Array)
#4 vendor/trails/trails.php(557): CourseController->edit_action('2a4373718e38db0...')
#5 app/controllers/studip_controller.php(116): Trails_Controller->perform('edit/2a4373718e...')
#6 vendor/trails/trails.php(154): StudipController->perform('edit/2a4373718e...')
#7 vendor/trails/trails.php(121): Trails_Dispatcher->map_uri_to_response('course/edit/2a4...')
#8 lib/plugins/core/StudIPPlugin.class.php(142): Trails_Dispatcher->dispatch('course/edit/2a4...')
#9 public/plugins.php(54): StudIPPlugin->perform('course/edit/2a4...')
#10 {main}`

**Comment by JFD23** [comment]
wenn ich dann die Veranstaltung erneut aufrufe hat das Verknüpfen aber geklappt...

**Comment by JFD23** [comment]
FYI
Plugin Version 1.14
getestet mit Stud.ip 42 und 45
