### ISSUE TITLE
Fehler im Cronjob

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#530]
Der Cronjob "Opencast - "Scheduled-Events-Refresh"" wurde deaktiviert, da bei der Ausführung ein Fehler aufgetreten ist.

Typ: InvalidArgumentException
Nachricht: CourseDate::room_assignment not found.
Code: 0
Stack trace:
  #$ lib/models/SimpleORMap.class.php(1350)
  #0 lib/models/SimpleORMap.class.php(1527): SimpleORMap->getValue('room_assignment')
  #1 public/plugins_packages/elan-ev/OpenCast/cronjobs/refresh_scheduled_events.php(91): SimpleORMap->__get('room_assignment')
  #2 lib/models/CronjobTask.class.php(112): RefreshScheduledEvents->execute('1', Array)
  #3 lib/models/CronjobSchedule.class.php(222): CronjobTask->engage('1', Array)
  #4 lib/classes/CronjobScheduler.class.php(339): CronjobSchedule->execute()
  #5 cli/cronjob-worker.php(34): CronjobScheduler->run()
  #6 {main}

**Comment by tgloeggl** [comment]
Da muss evtl. noch eine Weiche rein für ältere Stud.IP-Versionen
