### ISSUE TITLE
Fehler beim Cronjob Opencast - "Scheduled-Events-Refresh"

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-opencast-plugin#572]
Der Cronjob "Opencast - "Scheduled-Events-Refresh"" wurde deaktiviert, da bei der Ausführung ein Fehler aufgetreten ist.

Typ: InvalidArgumentException
Nachricht: CourseDate::room_booking not found.
Code: 0
Stack trace:
```
#$ lib/models/SimpleORMap.class.php(1366)
#0 lib/models/SimpleORMap.class.php(1514): SimpleORMap->getValue('room_booking')
#1 public/plugins_packages/elan-ev/OpenCast/cronjobs/refresh_scheduled_events.php(91): SimpleORMap->__get('room_booking')
#2 lib/models/CronjobTask.class.php(113): RefreshScheduledEvents->execute('1', Array)
#3 lib/models/CronjobSchedule.class.php(212): CronjobTask->engage('1', Array)
#4 lib/classes/CronjobScheduler.class.php(330): CronjobSchedule->execute()
#5 cli/cronjob-worker.php(34): CronjobScheduler->run()
#6 {main}
```

Vermutlich liegt es an unserem Stud.IP 4.1.5, das offiziell, laut `plugin.manifest` nicht mehr unterstützt wird.

**Comment by Rillke** [comment]
Vermutlich  wegen #530

**Comment by Rillke** [comment]
We upgraded Stud.IP now.
