### ISSUE TITLE
Error in Cronjob `refresh_scheduled_events`

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-opencast-plugin#778]
Der Cronjob "Opencast - "Scheduled-Events-Refresh"" wurde deaktiviert, da bei der Ausführung ein Fehler aufgetreten ist.

Typ: InvalidArgumentException
Nachricht: ResourceBooking::date not found.
Code: 0
Stack trace:
  #$ lib/models/SimpleORMap.class.php(1367)
  #0 lib/models/SimpleORMap.class.php(1549): SimpleORMap->getValue('date')
  #1 public/plugins_packages/elan-ev/OpenCast/cronjobs/refresh_scheduled_events.php(92): SimpleORMap->__get('date')
  #2 lib/models/CronjobTask.class.php(112): RefreshScheduledEvents->execute('1', Array)
  #3 lib/models/CronjobSchedule.class.php(222): CronjobTask->engage('1', Array)
  #4 lib/classes/CronjobScheduler.class.php(288): CronjobSchedule->execute()
  #5 cli/cronjob-worker.php(34): CronjobScheduler->run()
  #6 {main}

**Comment by tgloeggl** [comment]
https://github.com/elan-ev/studip-opencast-plugin/commit/e9883092b37e2b493ad76662a520c0b5688900bf
